name: Tic Tac Toe
on:
  issues:
    types: [opened]

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Play Tic Tac Toe
        uses: gadhagod/github-tictactoe@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          board-file: README.md
